# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('utility_provider', models.CharField(max_length=400)),
                ('account_number', models.CharField(blank=True, max_length=400, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.BooleanField(default=False)),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solargurus.EndUser')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(blank=True, max_length=200, null=True)),
                ('monitoring_and_maintenance', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_requirements', models.CharField(blank=True, max_length=200, null=True)),
                ('lien_specifics', models.CharField(blank=True, max_length=200, null=True)),
                ('cancellation_and_returns', models.CharField(blank=True, max_length=200, null=True)),
                ('relocation', models.CharField(blank=True, max_length=200, null=True)),
                ('shading_issues', models.CharField(blank=True, max_length=200, null=True)),
                ('upgrades', models.CharField(blank=True, max_length=200, null=True)),
                ('net_energy_metering', models.CharField(blank=True, max_length=200, null=True)),
                ('panel_efficiency', models.CharField(blank=True, max_length=200, null=True)),
                ('panel_country_of_origin', models.CharField(blank=True, max_length=200, null=True)),
                ('inverter_microinverter', models.CharField(blank=True, max_length=200, null=True)),
                ('energy_storage', models.CharField(blank=True, max_length=200, null=True)),
                ('suitable_roof_types', models.CharField(blank=True, max_length=200, null=True)),
                ('installation', models.CharField(blank=True, max_length=200, null=True)),
                ('referral_program', models.CharField(blank=True, max_length=200, null=True)),
                ('multiple_property_discounts', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solargurus.EndUser')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solargurus.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solargurus.Vendor'),
        ),
        migrations.AddField(
            model_name='package',
            name='commercial_purchasing_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='commercial_purchasing_options', to='solargurus.PurchasingOptions'),
        ),
        migrations.AddField(
            model_name='package',
            name='purchasing_options',
            field=models.ManyToManyField(related_name='purchasing_options', to='solargurus.PurchasingOptions'),
        ),
        migrations.AddField(
            model_name='package',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solargurus.Vendor'),
        ),
        migrations.AddField(
            model_name='loi',
            name='payment_methods',
            field=models.ManyToManyField(to='solargurus.PurchasingOptions'),
        ),
    ]
