# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enduser',
            options={'verbose_name': 'End User', 'verbose_name_plural': 'End Users'},
        ),
        migrations.AlterModelOptions(
            name='loi',
            options={'verbose_name': 'LOI', 'verbose_name_plural': 'LOIs'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterModelOptions(
            name='purchasingoptions',
            options={'verbose_name': 'Purchasing Option', 'verbose_name_plural': 'Purchasing Options'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
    ]
