# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0004_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
