# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0005_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loi',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
