# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0007_remove_proposal_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasingoptions',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
