# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0008_purchasingoptions_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Energy Advisor',
                'verbose_name_plural': 'Energy Advisors',
            },
        ),
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Real Estate Agent',
                'verbose_name_plural': 'Real Estate Agents',
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
