# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0009_auto_20170928_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loi',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, null=True, to='solargurus.PurchasingOptions'),
        ),
    ]
