# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0012_auto_20171008_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='energyadvisor',
            name='referral_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loi',
            name='referral_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagent',
            name='referral_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
    ]
