# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0013_auto_20171008_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='password',
            field=models.CharField(default='password', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enduser',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
