# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0014_auto_20171011_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
