# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0015_auto_20171011_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='enduser',
        ),
        migrations.AddField(
            model_name='proposal',
            name='loi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solargurus.LOI'),
            preserve_default=False,
        ),
    ]
