# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0016_auto_20171011_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Status Option',
                'verbose_name_plural': 'Status Options',
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='documents',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solargurus.StatusOptions'),
        ),
    ]
