# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0020_package_turn_around_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ground_mounts',
            field=models.NullBooleanField(),
        ),
    ]
