# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0022_energyadvisor_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='energy_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solargurus.EnergyAdvisor'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='real_estate_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solargurus.RealEstateAgent'),
        ),
    ]
