# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-23 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0024_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slogan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
