# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-23 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0026_vendor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='accolades',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='associations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
