# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-02 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0027_auto_20190423_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='additional_services',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='electric_vehicle_charging',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='installation_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='permitting',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
