# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0028_auto_20190502_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='general_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
