# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-14 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0030_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
