# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0033_auto_20190514_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='certified',
            field=models.BooleanField(default=False),
        ),
    ]
