# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0037_auto_20190818_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='associations',
        ),
        migrations.AddField(
            model_name='vendor',
            name='associations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
