# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0038_auto_20190818_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='associations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
