# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-26 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0040_auto_20190818_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='loi',
            name='roof_material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
