# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-03 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0041_loi_roof_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='ground_mounts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
