# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-06 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solargurus', '0042_auto_20190903_0022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('vendor', 'name')]),
        ),
    ]
