# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-15 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solargurus', '0045_auto_20191115_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCodesGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='OTP Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Opt Code',
                'verbose_name_plural': 'Generated Opt Codes',
            },
        ),
        migrations.RemoveField(
            model_name='optcodesgenerated',
            name='user',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='OTP Code'),
        ),
        migrations.DeleteModel(
            name='OptCodesGenerated',
        ),
    ]
